#!/bin/bash

trap ctrl_c INT

function ctrl_c() {
	echo ""
        echo "Saliendo...."
	exit
}


figlet -r Exallports
echo "$(tput setaf 6)									 @JoC7S "

if [[ -z $1 ]]
then
echo "Debe indicar la captura grapeable de nmap."
read -p "$(tput setaf 3)[$(tput setaf 1)*$(tput setaf 3)]$(tput setaf 3)Tambien puede iniciar un proceso de nmap si deseas (Y/N): " proceso
	if [[ $proceso == "Y" ]] || [[ $proceso == "y" ]]
	then
		read -p "$(tput setaf 3)Indica la ip para analizar: " an
		read -p "$(tput setaf 3)Indica el nombre del grapeable: " nombre
			if [[ -f $nombre ]]
			then
				echo ""
				echo "$(tput setaf 3)[$(tput setaf 1)*$(tput setaf 3)]$(tput setaf 3)El archivo grapeable ya existe en el directorio actual"
				echo ""
			fi
		echo "$(tput setaf 1)Esto puede tardar un poco..."
		nmap --stats-every 1s -sS -p- --min-rate 5000 -n $an -oG $nombre | grep -Eo '[0-9]{1,2}\.[0-9]{1,2}\%'
		
		
echo -n "$(tput setaf 3)Ip targeteada:$(tput setaf 1) " && cat $nombre | grep -oP '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sort -u
echo ""
echo -n "$(tput setaf 3)[$(tput setaf 1)-$(tput setaf 3)]$(tput setaf 3)Puertos filtrados:$(tput setaf 4) " && cat $nombre | grep -oP '\d{1,5}/filtered' | cut -d "/" -f 1 | xargs | tr ' ' ','
echo ""
echo -n "$(tput setaf 3)[$(tput setaf 1)+$(tput setaf 3)]$(tput setaf 3)Puertos abiertos:$(tput setaf 6) " && cat $nombre | grep -oP '\d{1,5}/open' | cut -d "/" -f 1 | xargs | tr ' ' ','
echo ""
exit
else
exit
	fi

fi

echo ""
echo -n "$(tput setaf 3)Ip targeteada:$(tput setaf 1) " && cat $1 | grep -oP '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sort -u
echo ""
echo -n "$(tput setaf 3)[$(tput setaf 1)-$(tput setaf 3)]$(tput setaf 3)Puertos filtrados:$(tput setaf 4) " && cat $1 | grep -oP '\d{1,5}/filtered' | cut -d "/" -f 1 | xargs | tr ' ' ','
echo ""
echo -n "$(tput setaf 3)[$(tput setaf 1)+$(tput setaf 3)]$(tput setaf 3)Puertos abiertos:$(tput setaf 6) " && cat $1 | grep -oP '\d{1,5}/open' | cut -d "/" -f 1 | xargs | tr ' ' ','
echo ""
